### ISSUE TITLE
vimeo-template.nsi生成的安装包，什么也没执行

### ISSUE THREAD

**Issue by cs1991** [winsoft666/NSIS-UI-Plugin#1]
编译后的提示：
1 warning:
8000: Page instfiles not used, no sections will be executed!

问题补充：
NSIS-UI-Plugin插件编译成功，运行脚本生成安装包，双击执行后，什么操作都没有；
我修改nsis-ui-plugin插件，在dll入口函数加了日志打印，发现dll没有调用成功。

**Comment by winsoft666** [comment]
1 warning:
8000: Page instfiles not used, no sections will be executed!

有这句警告的正常的，因为没有使用NSIS自带的安装流程

**Comment by winsoft666** [comment]
环境变量是否配置成功？
Visual Studio是否以管理员权限运行，否则生成后事件无权限拷贝文件。

**Comment by cs1991** [comment]
> 环境变量是否配置成功？
> Visual Studio是否以管理员权限运行，否则生成后事件无权限拷贝文件。

copy成功，在nsis的插件目录正常copy了dll
![Uploading image.png…]()
我加了日志，发现没有调用到

**Comment by rj1031cp** [comment]
我也出现这个问题了，请问是如何解决的 @cs1991
