### ISSUE TITLE
偶现写入注册表字段错误

### ISSUE THREAD

**Issue by chifandeyu** [winsoft666/NSIS-UI-Plugin#7]
有时候脚本写注册表，会出现写入内容错乱，写了不是我写入的内容，第二张图圈起来的是代码，不是写注册信息，但是莫名其妙会写到注册表了！
![ddd](https://user-images.githubusercontent.com/15946864/161115073-0de91ec5-10b5-4858-b538-28f262bbb506.jpg)
![ccc](https://user-images.githubusercontent.com/15946864/161115092-b19cbc49-3d65-4bca-bb47-23486d2751ae.jpg)

**Comment by chifandeyu** [comment]
非常疑惑，不知道是不是注册表写入内容为多线程操作，导致数据错乱了，没有人遇到这样的问题吗？

**Comment by chifandeyu** [comment]
https://raw.githubusercontent.com/winsoft666/NSIS-UI-Plugin/master/VimeoSetup/vimeo-template.nsi 的155行，是子线程调用，会偶现写入注册表数据错乱

**Comment by winsoft666** [comment]
注册表是可以多线程写入的，排查是否是其他方面的问题
